# Generated by Django 2.0.13 on 2019-12-12 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.SmallIntegerField(choices=[(1, '아침식사'), (2, '점심식사'), (3, '저녁식사')])),
                ('suggest_time', models.TimeField()),
                ('real_meal_time', models.TimeField()),
                ('food_type', models.TextField()),
                ('eat_together', models.SmallIntegerField(choices=[(1, '혼자'), (2, '함께')])),
                ('feeling', models.SmallIntegerField(choices=[(1, '좋아요'), (2, '괜찮아요'), (3, '별로에')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barundano.User'),
        ),
    ]
